// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VWStockApp.Services;

namespace VWStockApp.Services.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200827165121_spGetStockById")]
    partial class spGetStockById
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VWStockApp.Models.Body", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Bodies");
                });

            modelBuilder.Entity("VWStockApp.Models.CarModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BodyID")
                        .HasColumnType("int");

                    b.Property<int>("MakeID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("YearModel")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BodyID");

                    b.HasIndex("MakeID");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("VWStockApp.Models.Colour", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarModelID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("CarModelID");

                    b.ToTable("Colours");
                });

            modelBuilder.Entity("VWStockApp.Models.Feature", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("TrimLevelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TrimLevelID");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("VWStockApp.Models.Make", b =>
                {
                    b.Property<int>("MakeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MakeID");

                    b.ToTable("Makes");
                });

            modelBuilder.Entity("VWStockApp.Models.StockItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarModelID")
                        .HasColumnType("int");

                    b.Property<int?>("ColourID")
                        .HasColumnType("int");

                    b.Property<int?>("MakeID")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceModifier")
                        .HasColumnType("money");

                    b.Property<int?>("TrimLevelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CarModelID");

                    b.HasIndex("ColourID");

                    b.HasIndex("MakeID");

                    b.HasIndex("TrimLevelID");

                    b.ToTable("StockItem");
                });

            modelBuilder.Entity("VWStockApp.Models.TrimLevel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarModelID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("ID");

                    b.HasIndex("CarModelID");

                    b.ToTable("TrimLevels");
                });

            modelBuilder.Entity("VWStockApp.Models.CarModel", b =>
                {
                    b.HasOne("VWStockApp.Models.Body", "Body")
                        .WithMany()
                        .HasForeignKey("BodyID");

                    b.HasOne("VWStockApp.Models.Make", null)
                        .WithMany("CarModels")
                        .HasForeignKey("MakeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VWStockApp.Models.Colour", b =>
                {
                    b.HasOne("VWStockApp.Models.CarModel", null)
                        .WithMany("Colours")
                        .HasForeignKey("CarModelID");
                });

            modelBuilder.Entity("VWStockApp.Models.Feature", b =>
                {
                    b.HasOne("VWStockApp.Models.TrimLevel", null)
                        .WithMany("Features")
                        .HasForeignKey("TrimLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VWStockApp.Models.StockItem", b =>
                {
                    b.HasOne("VWStockApp.Models.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelID");

                    b.HasOne("VWStockApp.Models.Colour", "Colour")
                        .WithMany()
                        .HasForeignKey("ColourID");

                    b.HasOne("VWStockApp.Models.Make", "Make")
                        .WithMany()
                        .HasForeignKey("MakeID");

                    b.HasOne("VWStockApp.Models.TrimLevel", "TrimLevel")
                        .WithMany()
                        .HasForeignKey("TrimLevelID");
                });

            modelBuilder.Entity("VWStockApp.Models.TrimLevel", b =>
                {
                    b.HasOne("VWStockApp.Models.CarModel", null)
                        .WithMany("TrimLevels")
                        .HasForeignKey("CarModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
