INSERT INTO Colours(Name)
	VALUES	('Ascot Grey'),
			('Cherry Red'),
			('Deep Ocean Blue'),
			('Flash Red'),
			('Pure Grey'),
			('Pure White'),
			('Urano Grey'),
			('Teal Blue'),
			('Tornado Red'),
			('Moonlight Blue Pearlescent'),
			('Oryx White Pearlescent'),
			('Antimonial Blue Metallic'),
			('Atlantic Blue Metallic'),
			('Aquamatine Blue Metallic'),
			('Aqupulco Blue Metallic'),
			('Bamboo Garden Green'),
			('Bayleaf Green Metallic'),
			('Blackberry Metallic'),
			('Blue Silk Metallic'),
			('Carbon Stell Metallic'),
			('Chestnut Brown Metallic'),
			('Copper Bronze Metallic'),
			('Curcuma Yellow Metallic'),
			('Energetic Orange Metallic'),
			('Fortana Red Metallic'),
			('Honey Yellow Metallic'),
			('Indium Grey Metallic'),
			('Juniper Grey Metallic'),
			('Limestone Grey Metallic'),
			('Makena Turqois Metallic'),
			('Mojave Beige Metallic'),
			('Platinum Grey Metallic'),
			('Pyrite Silver Metallic'),
			('Ravena Blue Metallic'),
			('Reef Blue Metallic'),
			('Reflex Silver Metallic'),
			('Ruby Red Metallic'),
			('Sandstorm Yellow Metallic'),
			('Silicon Grey Metallic'),
			('Starlight Blue Metallic'),
			('Sunset Red Metallic'),
			('Tamarind Brown Metallic'),
			('Toffee Brown Metallic'),
			('Tungsten Silver Metallic'),
			('Viper Green Metallic'),
			('White Silver Metallic'),
			('Deep Black Pearlescent')
