INSERT INTO Features(TrimLevelID, Description)
	VALUES (1, 'Radio "Composition" Phone (includes Bluetooth)'),
			(1, 'USB interface'),
			(1, 'Smartphone integration: "maps & more" dock for smartphone'),
			(1, 'Sound "Plus" package: 4 additional speakers'),
			(1, 'Winter package (heated front seats & front fog lights) '),
			(2, 'Airbags'),
			(2, 'ISOFIX points'),
			(2, 'LED daytime running lights'),
			(2, 'Power Steering'),
			(2, 'Central Locking'),
			(3, '16" Rivazza Alloys in Anthracite'),
			(3, 'Radio system "RCD 340G"'),
			(3, 'Energetic Orange Mirror Covers'),
			(3, 'Subwoofer + 6 Speakers'),
			(4, 'Radio R340G BT/USB/SD'),
			(4, 'Chrome Tipped Exhaust Trim'),
			(4, 'Cruise Control'),
			(4, 'Front Sport Seats'),
			(4, 'Lowered Suspension'),
			(5, 'Radio R340G BT/USB/SD'),
			(5, '17" "Canyon" Alloy Wheel'),
			(5, 'Roof rails, silver-anodized'),
			(5, 'Aluminium Pedal cluster'),
			(5, 'Silver Painted Side Mirrors'),
			(6, 'Radio R340G BT/USB/SD'),
			(6, '16" "Rivazza" Alloy Wheel'),
			(6, '6 Speakers'),
			(6, 'Electronic Stability Control (ESC)'),
			(6, 'Leather Multi-Function Steering Wheel'),
			(6, 'Tyre Pressure Monitor'),
			(6, 'App-Connect'),
			(7, 'Radio R140G BT/USB/SD'),
			(7, '14" Steel Wheels'),
			(7, 'Multi-function steering wheel'),
			(7, 'Height Adjustable Driver''s Seat'),
			(7, 'Colour Coded Exterior Door Handles and Mirrors'),
			(8, 'Radio R140G BT/USB/SD'),
			(8, '14" Steel Wheels'),
			(8, 'ISOFIX anchorage points'),
			(8, 'Front Electric Windows'),
			(8, 'Immobilizer, with alarm system and interior monitoring'),
			(9, '230G Radio with CD, USB and SD card compatibility'),
			(9, '14" Steel wheels'),
			(9, 'Electric windows front and rear'),
			(10, '340G Radio with USB and SD card compatibility'),
			(10, '15" Tosa alloy wheels'),
			(10, 'Leather-wrapped multi-function steering wheel'),
			(10, 'Cruise control'),
			(10, 'Front fog lamps with cornering light function'),
			(11, '14" Steel Wheels'),
			(11, 'Electronic Stability Control'),
			(11, 'Front and Rear Curtain Airbags'),
			(11, 'LED Daytime Running Lights'),
			(11, 'Front Electric Windows'),
			(12, '15" "Salou" Alloy Wheels'),
			(12, '6 speakers'),
			(12, 'Rest Assist'),
			(12, 'Leather-wrapped multi-function steering wheel'),
			(12, 'Body-colored exterior mirror housings and door handles'),
			(12, 'Electric windows in front and rear'),
			(13, 'Radio "Composition Media"'),
			(13, '16" "Las Minas" Alloy Wheels'),
			(13, 'Front centre armrest'),
			(13, 'Cruise control system incl. speed limiter'),
			(13, 'App-Connect'),
			(13, 'Drive Profile Selection'),
			(14, 'Radio "Composition Media"'),
			(14, '17" "Milton Keynes" Alloy Wheels'),
			(14, 'GTI body kit '),
			(14, '"Art Velour" leather interior trim for seats and door trim'),
			(14, 'Dark red rear combination lamps in LED technology'),
			(14, 'EDS electronic differential lock'),
			(15, '15" Lyon alloy wheels'),
			(15, '6.5" Composition Colour touchscreen infotainment with MP3/USB/SD card and bluetooth'),
			(15, 'Start/stop system'),
			(15, 'Halogen headlights with LED daytime running lights and taillights'),
			(16, '16" Hita alloy wheels'),
			(16, '8" Composition Media Radio'),
			(16, 'Front center armrest storage compartment with 2 air-vents to rear passengers'),
			(16, 'Cruise control system'),
			(16, 'Front fog lamps with cornering lights function'),
			(16, 'Adjustable lumbar supports for front seats'),
			(17, '8" Composition Media Radio'),
			(17, 'LED headlights and daytime running lights with dynamic cornering function'),
			(17, 'GTI honeycomb front grille'),
			(17, 'Climatronic 2 zone airconditioner with allergen filter'),
			(18, '8" Composition Media Radio'),
			(18, '19" Spielberg alloy wheels with diamond-turned surface'),
			(18, '4Motion Permanent four-wheel-drive system'),
			(18, 'Panoramic sunroof'),
			(18, 'LED headlights and daytime running lights with dynamic cornering function'),
			(18, 'Digital instrument cluster -Active Info Display'),
			(18, 'R branded sill and bumper styling'),
			(18, 'Climatronic 2 zone airconditioner with allergen filter'),
			(19, 'Radio "Composition Media"'),
			(19, '4 alloy wheels "Reifnitz" 8J x 19, matte black'),
			(19, 'Adaptive Chassis Control DCC incl. Driving Profile Selection'),
			(19, 'Tilting and sliding panoramic sunroof, electric'),
			(19, 'Park Assist with Park Distance Control'),
			(20, 'Radio "Composition Colour"'),
			(20, '4 alloy wheels "Belmont" 6J x 16'),
			(20, 'Leather-wrapped multi-function steering wheel'),
			(20, 'Black roof rails'),
			(20, 'Park Distance Control - warning signals for obstacles in the front and rear'),
			(20, 'Cruise control system incl. speed limiter'),
			(21, 'Radio "Composition Media"'),
			(21, 'Driving Profile Selection'),
			(21, 'LED headlamps for low beam and high beam'),
			(21, 'Mobile phone interface with inductive charging function'),
			(21, 'Air conditioning system Climatronic'),
			(22, 'Radio "Composition Media"'),
			(22, '4 alloy wheels "Nevada" 7J x 18, Black, diamond-turned surface'),
			(22, 'Multi-color Active Info Display, selection of different info profiles possible'),
			(22, 'Driving Profile Selection'),
			(22, 'LED headlamps for low beam and high beam'),
			(22, 'Mobile phone interface with inductive charging function'),
			(23, 'Radio Composition Media'),
			(23, '4 alloy wheels "Mayfield" 7J x 17'),
			(23, 'Exterior mirrors, power-adjustable'),
			(23, 'Park Distance Control - warning signals for obstacles in the front and rear'),
			(23, 'App-Connect'),
			(23, 'Voice control'),
			(24, 'Radio Composition Media'),
			(24, '4 alloy wheels "Mayfield" 7J x 17'),
			(24, 'Exterior mirrors, power-adjustable'),
			(24, 'Park Distance Control - warning signals for obstacles in the front and rear'),
			(24, 'App-Connect'),
			(24, 'Voice control'),
			(25, 'Radio "Composition Colour"'),
			(25, '17" Montana alloy wheel'),
			(25, 'Black roof rails'),
			(25, 'Cruise control system with speed limiter'),
			(25, 'Multi-function display "Plus"'),
			(25, 'Climatic air conditioner'),
			(26, '8.0" Composition Media touchscreen infotainment system with USB, Bluetooth and 8 speakers'),
			(26, '17 "Tulsa Alloy Wheels'),
			(26, 'LED headlights and daytime running lights'),
			(26, 'Park Distance Control'),
			(26, 'Climatronic 3-zone Air Conditioner'),
			(26, 'High-beam Control "Light Assist"'),
			(27, '8.0" Touchscreen Radio "Composition Media" with MP3/WMA compatibility'),
			(27, '18" Kingston alloy wheels'),
			(27, 'Climatronic 3-zone Air Conditioner'),
			(27, 'LED headlights and daytime running lights'),
			(27, 'Chrome elements on the mirror adjustment and power window switches,'),
			(28, '17" "Montana" Alloy Wheels'),
			(28, 'ISOFIX child seat anchors'),
			(28, 'Electronic Stability Control'),
			(28, 'Halogen twin headlamps with LED daytime running lights'),
			(28, '8 speakers'),
			(29, '8.0" Touchscreen Radio "Composition Media" with MP3/WMA compatibility'),
			(29, '17 " "Tulsa" Alloy Wheels'),
			(29, 'LED headlamps with LED daytime running lights and dynamic cornering lights'),
			(29, 'Electric Tailgate'),
			(29, 'Park Distance Control'),
			(29, 'Air Care Climatronic 3 zone automatic climate control and controls in the rear'),
			(30, '8.0" Touchscreen Radio "Composition Media" with MP3/WMA compatibility'),
			(30, '18" "Kingston" Alloy Wheels'),
			(30, 'Keyless locking and starting system'),
			(30, 'Hill Descent Control'),
			(30, 'Chrome elements on the mirror adjustment and power window switches'),
			(31, 'Discover Pro Navigation system'),
			(31, '19" "Esperance" Alloy Wheels'),
			(31, 'LED headlamps with Light Assist main beam control'),
			(31, 'Adaptive Cruise Control ACC "stop & go" incl. speed limiter'),
			(31, 'Easy Open sensor controlled electric tailgate'),
			(31, 'ergoComfort front seats in Vienna leather, with seat heating, electric adjustment and memory function'),
			(32, 'Discover Pro Navigation System'),
			(32, '20" "Braga" Alloy Wheels'),
			(32, 'R-Line exterior and interior styling package'),
			(32, 'I.Q. Light - LED matrix headlamps'),
			(32, '4-corner air suspension with electronic shock absorption control and 4-wheel steering'),
			(32, 'Air Care Climatronic 4 zone automatic climate control with allergen filter and controls in the rear'),
			(33, 'Electronic Stability Control'),
			(33, '100% locking differential in rear, mechanical'),
			(33, 'Fuel tank with a volume of 80 l'),
			(33, 'Tailgate, lockable'),
			(33, '3-seater bench, folding, in 2nd row of seats'),
			(33, 'Power windows'),
			(33, 'Driver and front passenger airbags with front passenger airbag deactivation'),
			(33, 'Car-Net App-Connect'),
			(33, 'Mobile phone interface'),
			(33, 'Radio "Composition Media" with 6.33-inch touch screen'),
			(34, 'Electronic Stability Control'),
			(34, '100% locking differential in rear, mechanical'),
			(34, 'Fuel tank with a volume of 80 l'),
			(34, 'Tailgate, lockable'),
			(34, '3-seater bench, folding, in 2nd row of seats'),
			(34, 'Park distance control in front and rear with rear view camera system'),
			(34, 'Air conditioning system Climatronic'),
			(34, 'Seat trim covers in leather "Vienna"'),
			(34, 'Bi-xenon headlamps with separate LED daytime running lights and washer fluid level indicator'),
			(35, 'Four-wheel drive 4Motion (permanent)'),
			(35, 'Leather-wrapped multi-function steering wheel (3-spoke) with shifting paddles'),
			(35, '100% locking differential in rear, mechanical'),
			(35, 'Side and curtain airbags for driver and front passenger'),
			(35, 'Park distance control in front and rear with rear view camera system'),
			(35, 'Car-Net App-Connect'),
			(35, '8-speed automatic transmission for four-wheel drive'),
			(35, 'Load compartment coating, resistant to abrasion and stone impact, UV-resistant, anthracite'),
			(35, 'Seat heater for driver seat and front passenger seat, separately controllable'),
			(35, 'Car-Net App-Connect'),
			(36, 'Electronic Stability Control'),
			(36, '100% locking differential in rear, mechanical'),
			(36, 'Fuel tank with a volume of 80 l'),
			(36, 'Tailgate, lockable'),
			(36, '3-seater bench, folding, in 2nd row of seats'),
			(36, 'Power windows'),
			(36, 'Driver and front passenger airbags with front passenger airbag deactivation'),
			(36, 'Car-Net App-Connect'),
			(36, 'Radio "Composition Media" with 6.33-inch touch screen'),
			(36, '"Dark Label" SA'),
			(36, 'Alloy wheels "Rawson" 7.5J x 18, anthracite, diamond-turned surface - Mileage -'),
			(37, 'Front side windows in heat-insulating glass, rear side windows and rear window in privacy glass'),
			(37, 'Leather-wrapped multi-function steering wheel (3-spoke)'),
			(37, 'Driver and front passenger airbags with front passenger airbag deactivation'),
			(37, 'Exterior mirrors, power-adjustable, heated and folding'),
			(37, 'Bi-xenon headlamps with separate LED daytime running lights'),
			(37, 'Air conditioning system Climatronic'),
			(37, 'Seat trim covers in special edition Canyon'),
			(37, '6-cylinder diesel engine 3.0 l unit 059.L'),
			(37, 'Add-on kit wider wheel arch cover'),
			(38, 'Short wheelbase'),
			(38, 'Front-wheel drive'),
			(38, 'Halogen headlamps'),
			(38, 'Steel wheels 6J x 15'),
			(38, '5-speed manual transmission'),
			(38, 'Panel Van'),
			(38, 'Tire pressure monitoring system'),
			(39, 'Long wheelbase'),
			(39, 'Front-wheel drive'),
			(39, 'Anti-theft alarm system, interior monitoring, backup horn, and towing protection'),
			(39, 'Tire pressure monitoring system'),
			(39, 'Halogen headlamps'),
			(39, 'Smoker''s package'),
			(39, 'Trendline'),
			(39, 'Electronically controlled air conditioning system'),
			(39, 'Trailer hitch'),
			(39, 'Body-colored protective side molding'),
			(39, 'Electronic cruise control system (CCS)'),
			(39, 'Alloy wheels "Fortaleza" 6J x 16'),
			(40, 'All-season tires 205/55 R16 94H xl super-low rolling resistance'),
			(40, 'Halogen headlamps'),
			(40, 'Anti-theft alarm system, interior monitoring, backup horn, and towing protection'),
			(40, 'Electronically controlled air conditioning system'),
			(40, 'MIB2-G Ultralow NF PQ/MQB radio EU'),
			(41, 'All-season tires 205/55 R16 94H xl super-low rolling resistance'),
			(41, 'Halogen headlamps'),
			(41, 'Anti-theft alarm system, interior monitoring, backup horn, and towing protection'),
			(41, 'Electronically controlled air conditioning system'),
			(41, 'MIB2-G Ultralow NF PQ/MQB radio EU'),
			(42, 'All-season tires 205/55 R16 94H xl super-low rolling resistance'),
			(42, 'Halogen headlamps'),
			(42, 'Anti-theft alarm system, interior monitoring, backup horn, and towing protection'),
			(42, 'Electronically controlled air conditioning system'),
			(42, 'MIB2-G Ultralow NF PQ/MQB radio EU'),
			(43, 'All-season tires 205/55 R16 94H xl super-low rolling resistance'),
			(43, 'Halogen headlamps'),
			(43, 'Anti-theft alarm system, interior monitoring, backup horn, and towing protection'),
			(43, 'Electronically controlled air conditioning system'),
			(43, 'MIB2-G Ultralow NF PQ/MQB radio EU'),
			(44, '16-inch chassis'),
			(44, 'All-season tires 205/55 R16 94H xl super-low rolling resistance'),
			(44, 'Acoustics package "Extra"'),
			(44, 'Park distance control'),
			(44, 'Smoker''s package'),
			(45, '16-inch chassis'),
			(45, 'All-season tires 205/55 R16 94H xl super-low rolling resistance'),
			(45, 'Acoustics package "Extra"'),
			(45, 'Park distance control'),
			(45, 'Smoker''s package'),
			(46, '16-inch chassis'),
			(46, 'All-season tires 205/55 R16 94H xl super-low rolling resistance'),
			(46, 'Acoustics package "Extra"'),
			(46, 'Park distance control'),
			(46, 'Smoker''s package'),
			(47, '16-inch chassis'),
			(47, 'All-season tires 205/55 R16 94H xl super-low rolling resistance'),
			(47, 'Acoustics package "Extra"'),
			(47, 'Park distance control'),
			(47, 'Smoker''s package'),
			(48, '17" "Quito" Alloy wheels'),
			(48, 'Composition Media Touchscreen Radio with USB, Bluetooth, SD card and CD Player'),
			(48, 'Folding table on front seat backrests'),
			(48, 'Roof rails, painted in silver'),
			(48, 'Side and curtain air bags for driver and front passenger'),
			(48, 'Cruise control'),
			(48, 'Front heated seats'),
			(48, 'Drawers under front seats'),
			(49, '16" steel wheels in 20-hole style'),
			(49, '"Composition Audio" radio with USB, SD Card and Bluetooth.'),
			(49, 'Step illumination in passenger/load compartment'),
			(49, 'Climatic A/C system'),
			(49, 'Rigid trailer hitch with Electronic Stability Program'),
			(49, '8 Seats'),
			(49, 'Driver''s and front passenger air bag'),
			(50, 'Step illumination in passenger/load compartment'),
			(50, 'Climatic A/C system'),
			(50, 'Rigid trailer hitch with Electronic Stability Program'),
			(50, '8 Seats'),
			(50, 'Driver''s and front passenger air bag'),
			(50, 'Park distance control, acoustic warning signal for obstacles in the front and rear'),
			(50, 'Cruise control'),
			(50, 'Radio "Composition Colour" with 5-inch touch screen, USB, Bluetooth and 6 Speakers'),
			(50, '16" "Clayton" Alloy wheels'),
			(51, '17" "Devonport" Alloy wheels'),
			(51, '7-speed DSG transmission'),
			(51, 'Sunshades for side windows in passenger compartment'),
			(51, 'Driver''s and front passenger air bag'),
			(51, 'Anti-theft alarm system and backup horn'),
			(51, 'Cruise control'),
			(51, '"Pandu" fabric seat trim covers'),
			(52, 'Trailer hitch, removable and lockable'),
			(52, 'Start-stop system with regenerative braking'),
			(52, 'Lane change assist'),
			(52, 'LED headlamps with lens'),
			(52, 'Cruise control system and speed limiter'),
			(52, 'Comfort telephony with LTE and wireless charging'),
			(52, '7-speed automatic transmission for four-wheel drive'),
			(53, 'Dark tinted glass in rear seat area (Venus 35/Privacy) heat-insulating glass (green) in front'),
			(53, 'Alloy wheels 7J x 17'),
			(53, 'With Build-in Cupboard Type 7 Cupboards in "Bright Oak"'),
			(53, 'Navigation system MIB2 Standard PQ (EU/ROW)'),
			(53, 'Start-stop system with regenerative braking'),
			(54, 'Long wheelbase'),
			(54, 'Gross vehicle weight rating: 3 000 kg'),
			(54, 'Dust and pollen filter'),
			(54, '2-seater front passenger bench on the left, in 1st row of seats'),
			(54, 'Central locking system with radio remote control and interior release mechanism'),
			(54, 'Air conditioning system Climatic in cab'),
			(54, 'Radio "Composition Audio" with thin film transistor LCD (monochrome)'),
			(55, 'Long wheelbase'),
			(55, 'Gross vehicle weight rating: 3 000 kg'),
			(55, 'Dust and pollen filter'),
			(55, 'Central locking system with radio remote control and interior release mechanism'),
			(55, 'Air conditioning system Climatic in cab'),
			(55, 'Radio "Composition Audio" with thin film transistor LCD (monochrome)'),
			(56, 'Standard EPS, ABS, TCS and EBD'),
			(56, '75 litre fuel tank'),
			(56, 'Air conditioning system Climatic'),
			(56, 'Cruise control system and speed limiter')